// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFn-DBlBV2kqyBoC1HNF7EjJuFWKB4rjo',
    appId: '1:104551526098:web:52a2937e2e4fb25913c70b',
    messagingSenderId: '104551526098',
    projectId: 'kgms-de0e8',
    authDomain: 'kgms-de0e8.firebaseapp.com',
    databaseURL: 'https://kgms-de0e8-default-rtdb.firebaseio.com',
    storageBucket: 'kgms-de0e8.firebasestorage.app',
    measurementId: 'G-VSY72KZ05P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLZHqMhVTF66FfqkCBDEdiVAHWSu7iOQ4',
    appId: '1:104551526098:android:01cf82db69a98b3513c70b',
    messagingSenderId: '104551526098',
    projectId: 'kgms-de0e8',
    databaseURL: 'https://kgms-de0e8-default-rtdb.firebaseio.com',
    storageBucket: 'kgms-de0e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcuYSluQbUzFr-D926THMKuvBqKMkidco',
    appId: '1:104551526098:ios:35c6a4a31de3f6a513c70b',
    messagingSenderId: '104551526098',
    projectId: 'kgms-de0e8',
    databaseURL: 'https://kgms-de0e8-default-rtdb.firebaseio.com',
    storageBucket: 'kgms-de0e8.firebasestorage.app',
    iosBundleId: 'com.ecommerce.kiibazaar.user.kiiBazaar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcuYSluQbUzFr-D926THMKuvBqKMkidco',
    appId: '1:104551526098:ios:35c6a4a31de3f6a513c70b',
    messagingSenderId: '104551526098',
    projectId: 'kgms-de0e8',
    databaseURL: 'https://kgms-de0e8-default-rtdb.firebaseio.com',
    storageBucket: 'kgms-de0e8.firebasestorage.app',
    iosBundleId: 'com.ecommerce.kiibazaar.user.kiiBazaar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFn-DBlBV2kqyBoC1HNF7EjJuFWKB4rjo',
    appId: '1:104551526098:web:d4285e93e1575c1c13c70b',
    messagingSenderId: '104551526098',
    projectId: 'kgms-de0e8',
    authDomain: 'kgms-de0e8.firebaseapp.com',
    databaseURL: 'https://kgms-de0e8-default-rtdb.firebaseio.com',
    storageBucket: 'kgms-de0e8.firebasestorage.app',
    measurementId: 'G-PNRB1E3G9K',
  );
}
